---
- hosts: all
  become: yes
  tasks:
    - name: Install Java 8
      yum:
        name: java-1.8.0-openjdk
        state: present
       when: ansible_distribution == 'Debian' or ansible_distribution == 'Fedora'
    - name: Download Sonatype Nexus Repository Manager
      get_url:
        url: https://download.sonatype.com/nexus/3/nexus-3.21.1-02-unix.tar.gz
        dest: /opt/nexus-3.21.1-02-unix.tar.gz
       when: ansible_distribution == 'Debian' or ansible_distribution == 'Fedora'
    - name: Extract Sonatype Nexus Repository Manager
      unarchive:
        src: /opt/nexus-3.21.1-02-unix.tar.gz
        dest: /opt/nexus
       when: ansible_distribution == 'Debian' or ansible_distribution == 'Fedora'
    - name: Create Nexus user and group
      user:
        name: nexus
        group: nexus
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Fedora'
    - name: Change ownership of Nexus home directory
      file:
        path: /opt/nexus
        owner: nexus
        group: nexus
       when: ansible_distribution == 'Debian' or ansible_distribution == 'Fedora'
    - name: Create Nexus systemd service file
      template:
        src: nexus.service.j2
        dest: /etc/systemd/system/nexus.service
       when: ansible_distribution == 'Debian' or ansible_distribution == 'Fedora'
    - name: Reload systemd configuration
      systemd:
        daemon_reload: yes
       when: ansible_distribution == 'Debian' or ansible_distribution == 'Fedora'
    - name: Start Nexus service
      service:
        name: nexus
        state: started
       when: ansible_distribution == 'Debian' or ansible_distribution == 'Fedora'
    - name: Enable Nexus service to start on boot
      systemd:
        name: nexus
        enabled: yes
       when: ansible_distribution == 'Debian' or ansible_distribution == 'Fedora'
    - name: Use URI module to interact with the NXRM REST API and create one Docker and one Raw repository
      uri:
        url: http://localhost:8081/service/rest/v1/repositories
        method: POST
        body: '{ "name": "docker-repo", "type": "docker", "format": "docker" }'
        body_format: json
        status_code: 201
       when: ansible_distribution == 'Debian' or ansible_distribution == 'Fedora'
      uri:
        url: http://localhost:8081/service/rest/v1/repositories
        method: POST
        body: '{ "name": "raw-repo", "type": "raw", "format": "raw" }'
        body_format: json
        status_code: 201
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Fedora'